### ISSUE TITLE
Invalid bg/fg color pairs at: COLOR_MTRC_HITS after update to 0.9.3

### ISSUE THREAD

**Issue by sanderheilbron** [allinurl/goaccess#293]
Any idea how to fix the following error?

Fatal error has occurred
Error occured at: src/color.c - parse_color_line - 580
Invalid bg/fg color pairs at: COLOR_MTRC_HITS color7:color-1

**Comment by allinurl** [comment]
What OS are you running?

**Comment by sanderheilbron** [comment]
OS X Yosemite

**Comment by allinurl** [comment]
Thanks for reporting this. This is due to a missing POSIX extension #286. I fixed this upstream. If you are using brew you can use: 
 
    brew install --HEAD goaccess

I'll be pushing a minor release pretty soon.

**Comment by sanderheilbron** [comment]
I just did an install using brew, it runs without issues now.

Thanks!

**Comment by edfield** [comment]
Same problem on Debian 8.1

Fatal error has occurred
Error occured at: src/color.c - parse_color_line - 580
Invalid bg/fg color pairs at: COLOR_MTRC_HITS color7:color-1

**Comment by allinurl** [comment]
@edfield Can you please try to build from [master](http://goaccess.io/download#build)? Just to make sure the fix will work before the new release. Thanks

**Comment by edfield** [comment]
I installed from packages. After the error I went back to the older version, 0.8.3, and all works fine again.  

Tried to build from master as you asked, but got this error and not sure how to fix it.

./configure --enable-geoip --enable-utf8

 error:
     *** pkg-config script could not be found. Make sure it is
     *** in your path, or set the PKG_CONFIG environment variable
     *** to the full path to pkg-config. Otherwise, reinstall glib2
     *** development files (libglib2.0-dev)

     installed libglib2.0-dev
 apt-get install libglib2.0-dev

./configure --enable-geoip --enable-utf8

error: *** Missing development libraries for GLib

**Comment by allinurl** [comment]
@edfield After running `apt-get install libglib2.0-dev`, you will need to run: 

    $ autoreconf -fiv
    $ ./configure --enable-geoip --enable-utf8
    $ make
    # make install

Thanks!

**Comment by edfield** [comment]
That fixed it. 

Runs fine after completing build

**Comment by allinurl** [comment]
Great! So I'll deploy the new release pretty soon. Thanks!

**Comment by edfield** [comment]
Just discovered a bit of strangeness. It works when running it from a remote terminal. When I run it from the console, the error comes back.

**Comment by allinurl** [comment]
Feel free to rebase from master. This has been fixed.

Thanks again for pointing that out.

**Comment by edfield** [comment]
Works great after building again.

**Comment by netgurru** [comment]
Hi, I am on CentOS 5.10 and getting same error

Fatal error has occurred
Error occured at: src/color.c - parse_color_line - 580
Invalid bg/fg color pairs at: COLOR_MTRC_HITS color0:color-1

**Comment by allinurl** [comment]
@netgurru It's likely you are running an old version of autoconf. I've changed the build script, please rebase from master and try again.

**Comment by allinurl** [comment]
This has been fixed and deployed.

**Comment by domhnallw** [comment]
This is still happening for me. goaccess 0.9.3 on OS X Yosemite.

Installed using brew: `brew install goaccess`. Getting the same issue:

```
$ goaccess -f access.log

GoAccess - version 0.9.3 - Aug 29 2015 06:57:09
Config file: /usr/local/Cellar/goaccess/0.9.3/etc/goaccess.conf

Fatal error has occurred
Error occured at: src/color.c - parse_color_line - 580
Invalid bg/fg color pairs at: COLOR_MTRC_HITS color7:color-1
```

Tried `brew install --HEAD goaccess` as per this thread and got:
`Warning: goaccess-0.9.3 already installed`

Here's what happened when I did the original install, may be helpful:

```
$ brew install goaccess
==> Installing dependencies for goaccess: gettext, libffi, glib
==> Installing goaccess dependency: gettext
==> Downloading https://homebrew.bintray.com/bottles/gettext-0.19.6.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gettext-0.19.6.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides the BSD gettext library and some software gets confused if both are in the library path.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/gettext/lib
    CPPFLAGS: -I/usr/local/opt/gettext/include

==> Summary
🍺  /usr/local/Cellar/gettext/0.19.6: 1921 files, 22M
==> Installing goaccess dependency: libffi
==> Downloading https://homebrew.bintray.com/bottles/libffi-3.0.13.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libffi-3.0.13.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Some formulae require a newer version of libffi.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/libffi/lib

==> Summary
🍺  /usr/local/Cellar/libffi/3.0.13: 14 files, 412K
==> Installing goaccess dependency: glib
==> Downloading https://homebrew.bintray.com/bottles/glib-2.46.0.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring glib-2.46.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/glib/2.46.0: 416 files, 18M
==> Installing goaccess
==> Downloading https://homebrew.bintray.com/bottles/goaccess-0.9.3.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring goaccess-0.9.3.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/goaccess/0.9.3: 10 files, 268K
```

**Comment by allinurl** [comment]
@domhnallw This was fixed in [v0.9.4](https://raw.githubusercontent.com/allinurl/goaccess/master/ChangeLog).

It seems like the the [formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/goaccess.rb) hasn't been updated. Can you try the following:
 
    brew reinstall --HEAD goaccess

or uninstalling it:

    brew cleanup goaccess
    brew install --HEAD goaccess

**Comment by domhnallw** [comment]
`brew reinstall --HEAD goaccess` produced this:

```
$ brew reinstall --HEAD goaccess
==> Reinstalling goaccess
==> Installing dependencies for goaccess: autoconf, automake, pkg-config
==> Installing goaccess dependency: autoconf
==> Downloading https://homebrew.bintray.com/bottles/autoconf-2.69.yosemite.bottle.4.tar.gz
######################################################################## 100.0%
==> Pouring autoconf-2.69.yosemite.bottle.4.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
/usr/local/share/emacs/site-lisp/

Add the following to your init file to have packages installed by
Homebrew added to your load-path:
(let ((default-directory "/usr/local/share/emacs/site-lisp/"))
  (normal-top-level-add-subdirs-to-load-path))
==> Summary
🍺  /usr/local/Cellar/autoconf/2.69: 70 files, 3.1M
==> Installing goaccess dependency: automake
==> Downloading https://homebrew.bintray.com/bottles/automake-1.15.yosemite.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring automake-1.15.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/automake/1.15: 130 files, 3.2M
==> Installing goaccess dependency: pkg-config
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.28.yosemite.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring pkg-config-0.28.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.28: 10 files, 612K
==> Installing goaccess
==> Cloning https://github.com/allinurl/goaccess.git
Cloning into '/Library/Caches/Homebrew/goaccess--git'...
remote: Counting objects: 67, done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 67 (delta 11), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (67/67), done.
Checking connectivity... done.
==> Checking out branch master
==> autoreconf -vfi
==> ./configure --prefix=/usr/local/Cellar/goaccess/HEAD
Last 15 lines from /Users/me/Library/Logs/Homebrew/goaccess/02.configure:
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/private/tmp/goaccess20150924-44795-3ozdk9':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
$
```

Getting the same error if I try to uninstall and reinstall.

I do have Xcode installed (including the command line tools, as far as I know), so I'm confused.

The relevant section from the abovementioned `config.log` says:

```
## ----------- ##
## Core tests. ##
## ----------- ##

configure:2294: checking for a BSD-compatible install
configure:2362: result: /usr/bin/install -c
configure:2373: checking whether build environment is sane
configure:2428: result: yes
configure:2579: checking for a thread-safe mkdir -p
configure:2618: result: ./install-sh -c -d
configure:2625: checking for gawk
configure:2655: result: no
configure:2625: checking for mawk
configure:2655: result: no
configure:2625: checking for nawk
configure:2655: result: no
configure:2625: checking for awk
configure:2641: found /usr/bin/awk
configure:2652: result: awk
configure:2663: checking whether make sets $(MAKE)
configure:2685: result: yes
configure:2714: checking whether make supports nested variables
configure:2731: result: yes
configure:2914: checking for gcc
configure:2941: result: clang
configure:3170: checking for C compiler version
configure:3179: clang --version >&5
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
configure:3190: $? = 0
configure:3179: clang -v >&5
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
configure:3190: $? = 0
configure:3179: clang -V >&5
clang: error: unsupported option '-V -isysroot'
configure:3190: $? = 1
configure:3179: clang -qversion >&5
clang: error: unknown argument: '-qversion'
clang: warning: no such sysroot directory: ''
configure:3190: $? = 1
configure:3210: checking whether the C compiler works
configure:3232: clang    conftest.c  >&5
clang: warning: no such sysroot directory: ''
configure:3236: $? = 0
configure:3284: result: yes
configure:3287: checking for C compiler default output file name
configure:3289: result: a.out
configure:3295: checking for suffix of executables
configure:3302: clang -o conftest    conftest.c  >&5
clang: warning: no such sysroot directory: ''
configure:3306: $? = 0
configure:3328: result:
configure:3350: checking whether we are cross compiling
configure:3358: clang -o conftest    conftest.c  >&5
clang: warning: no such sysroot directory: ''
conftest.c:11:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
configure:3362: $? = 1
configure:3369: ./conftest
./configure: line 3371: ./conftest: No such file or directory
configure:3373: $? = 127
configure:3380: error: in `/private/tmp/goaccess20150924-45554-msygpk':
configure:3382: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

It looks like the C compiler is misconfigured, broken, or missing??

**Comment by allinurl** [comment]
Interesting... I can suggest trying:

    brew uninstall $(brew deps goaccess)
    brew install --HEAD goaccess

**Comment by domhnallw** [comment]
Same problem, except for the missing geoip package:

```
$ brew uninstall $(brew deps goaccess)
Error: No such keg: /usr/local/Cellar/geoip
$ brew install --HEAD goaccess
==> Cloning https://github.com/allinurl/goaccess.git
Updating /Library/Caches/Homebrew/goaccess--git
==> Checking out branch master
==> autoreconf -vfi
==> ./configure --prefix=/usr/local/Cellar/goaccess/HEAD
Last 15 lines from /Users/me/Library/Logs/Homebrew/goaccess/02.configure:
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/private/tmp/goaccess20150924-46371-12ez093':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
$
```

**Comment by allinurl** [comment]
It looks like it's on a bad cycle... I don't have a mac in hand, but you could try [this](http://stackoverflow.com/a/28240901).

**Comment by domhnallw** [comment]
@allinurl Thanks, but no joy. Same as before.

**Comment by allinurl** [comment]
Since it appears to be an issue with homebrew, you may want to open an issue [here](https://github.com/Homebrew/homebrew/issues).

**Comment by kliker** [comment]
`brew reinstall --HEAD goaccess` resolved this issue for me on OS X Yosemite

**Comment by domhnallw** [comment]
@allinurl Okay I'll look into that, thanks.

**Comment by nicolasln** [comment]
Had the same issue on Yosemite and `brew reinstall --HEAD goaccess` fixed it for me as well.

**Comment by domhnallw** [comment]
It now works with goaccess-0.9.4 on yosemite.

**Comment by allinurl** [comment]
@domhnallw great, it looks like the [formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/goaccess.rb) was updated to v0.9.4 as well.

**Comment by domhnallw** [comment]
@allinurl Yep, it was. I uninstalled and re-installed the new formula and it worked first time. Thanks very much.
