### ISSUE TITLE
Web access returns 400 Invalid Request

### ISSUE THREAD

**Issue by realies** [allinurl/goaccess#969]
Running the following `docker run -p 7890:7890 -v "/mnt/user/appdata/goaccess/data":"/srv/data":rw -v "/mnt/user/appdata/goaccess/html":"/srv/report":rw -v "/mnt/user/appdata/letsencrypt/log/nginx":"/srv/logs":ro allinurl/goaccess goaccess /srv/logs/access.log -o report.html --real-time-html --no-global-config --config-file=/srv/data/goaccess.conf` parses the access log and returns `WebSocket server ready to accept new client connections`.

Unfortunately accessing the the front-end results in an empty page, curl confirms:
```
# curl http://localhost:7890/ -vvvv
*   Trying localhost...
* TCP_NODELAY set
* Connected to localhost (localhost) port 7890 (#0)
> GET / HTTP/1.1
> Host: localhost:7890
> User-Agent: curl/7.57.0
> Accept: */*
> 
< HTTP/1.1 400 Invalid Request
* no chunk, no close, no size. Assume close to signal end
< 
* Closing connection 0
```

Using different ports for the front-end and the WebSocket server (`--ws-url=0.0.0.0:7891 --port=7890`)produces the same result.

**Comment by thornyweb** [comment]
Did you ever find a solution to this? I'm seeing it now.

**Comment by 1arrow** [comment]
following

**Comment by allinurl** [comment]
@1arrow @thornyweb are you able to run and debug this outside of Docker? I'm thinking it should be fairly easy to debug this on gdb. Let me know and I can post some steps on how to do this. Thanks

**Comment by realies** [comment]
@thornyweb, just tested my instance and it seems I still haven't found a way around it.

**Comment by allinurl** [comment]
@realies So just to be clear, if you run goaccess outside Docker, then you are able to get real-time data? 

I'm thinking this most be some sort configuration or version issue since I'm able to run goaccess in a Docker container while getting real-time data out of it. Again, if any of you are able to reproduce this issue outside of Docker and run it through gdb would be awesome.

**Comment by thornyweb** [comment]
@allinurl I can run it in docker with out the real time html flag and it runs ok it’s the real time html flag that seems to be causing me problems.

@realies are you saying that you use a volume to mount the report html and then serve that on your Docker host with Nginx?

**Comment by realies** [comment]
@thornyweb, it seems that `goaccess` does not serve the HTML report page and the exposed port is meant for WebSocket connections only.  Serving the HTML report file via a web server does work as long as the WebSocket port is correctly exposed from the container to the serving host.

My expectation for the default behaviour is that`goaccess` is accessible via its port and responding with the report page when accessed via HTTP and providing the WebSocket connection if accessed via WS.

**Comment by allinurl** [comment]
That's right. You need to serve the HTML report through a web server, e.g., nginx, apache, etc. or open the HTML file via your browser (Ctrl+o), i.e.,  `file:///srv/report/report.html`. You can find more details [**here**](https://github.com/allinurl/goaccess#docker).

**Comment by realies** [comment]
Would it be difficult to host the HTML file via the same port?

**Comment by thornyweb** [comment]
Thanks @allinurl

@realies. Having had this confirmed now. I think the easiest thing to do would be to mount the reports dir in as a volume from your host then run nginx as a separate service, both could be defined in a single compose file which could use the same volume from the host.

**Comment by realies** [comment]
Sure, would be cool if `proxy_pass` is the only thing needed, similarly to other containerised web apps.

**Comment by thornyweb** [comment]
@realies This is my compose file I've got working locally with Docker

```
version: "3.2"
services:
  nginx:
   container_name: goaccess_web
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - C:/Users/Michael/Dev/projects/goaccess/LOCAL/html:/usr/share/nginx/html:ro

  app:
    container_name: goaccess_service
    image: allinurl/goaccess:latest
    ports:
      - 7890:7890
    volumes:
      - C:/Users/Michael/Dev/projects/goaccess/LOCAL/data:/srv/data
      - C:/Users/Michael/Dev/projects/goaccess/LOCAL/logs:/srv/logs
      - C:/Users/Michael/Dev/projects/goaccess/LOCAL/html:/srv/report

Then just going to http://localhost hits the nginx and serves the html.

**Comment by realies** [comment]
Thanks for this but my point is that perhaps with little modification of `goaccess` there wouldn't be any need for a webserver when there is already a websocket server built-in.

**Comment by allinurl** [comment]
The original assumption was that if you're parsing an access log, you probably have a webserver that you could use to serve the HTML file. That probably doesn't hold completely in a Docker environment.. There was a discussion to have a built-in [web server](https://github.com/allinurl/goaccess/issues/724#issuecomment-294307256) to simply serve the HTML file. I still need to look into this.

@thornyweb, please feel free to submit a PR and I'll be happy to merge it and update the docs. Thanks.

**Comment by BirkhoffLee** [comment]
I'm also having a same issue of WebSocket connection returning 400 Invalid Request. I'm not sure but should there be any additional messages in log when a successful WS connection establishes? I only have this:
```
$ docker-compose logs -f goaccess
Attaching to goaccess_goaccess_1
WebSocket server ready to accept new client connections
```

and +1 for 
> It just seems more elegant to provide the html via the same port if it is relatively easy to implement.

**Comment by BirkhoffLee** [comment]
After some testing, having **any** cookies sent to WS server will result in a 400 Bad Request error returning from the WS server. The solution is to (simply) clear all cookies that will be sent to the server and try again. It worked for me :)

**Comment by Ehekatl** [comment]
I don't have any cookie, still get 400 no matter how I configure (I have tried all means on readme, including different platform docker/linux/macos, curl & chrome never works, raw websocket does work use client like wsta)

**Comment by allinurl** [comment]
@BirkhoffLee Are you able to provide the steps to reproduce this? So far I'm unable to replicate this from my side.

@Ehekatl Are you running it inside a Docker container as well?

**Comment by Ehekatl** [comment]
@allinurl either it's inside docker or outside, it's always http 400

I don't think docker matters, I have experience running a lot application inside docker, including websocket ones.

It should be some simple mistake during websocket http handshake, since raw websockets always work.
Another issue I'm not sure if it's related, `goaccess access.log -o /tmp/report.html --real-time-html` running goaccess like this, the report.html won't get update unless I restart goaccess

**Comment by Ehekatl** [comment]
@allinurl finally I'm able to reproduce this bug 100% time.

ws server return http 400 when cookie is larger than a certain size.

I can reproduce this by request with a large cookie

**Comment by allinurl** [comment]
@Ehekatl Thanks for posting this finding. Just to be sure, so no cookie it works, large cookie doesn't work? Can you please share the length of the cookie you are sending so I can play with it from my side? Thanks!

**Comment by ltm** [comment]
@allinurl I just experienced this issue as well. I believe it occurs when the total size of the request is larger than 1024 bytes, which is likely to happen if you have several cookies already set for the domain.

As such, a request of 1025 bytes (note `printf '%819s'`) returns 400:
```
$ curl -v http://localhost:7890/ \
    -H 'Connection: Upgrade' \
    -H 'Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==' \
    -H 'Sec-WebSocket-Version: 13' \
    -H 'Upgrade: websocket' \
    -H 'User-Agent: Mozilla/5.0' \
    -H 'Cookie: foo='$(printf '%819s' | tr ' ' 'x')
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 7890 (#0)
> GET / HTTP/1.1
> Host: localhost:7890
> Accept: */*
> Connection: Upgrade
> Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==
> Sec-WebSocket-Version: 13
> Upgrade: websocket
> User-Agent: Mozilla/5.0
> Cookie: foo=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 
< HTTP/1.1 400 Invalid Request
* no chunk, no close, no size. Assume close to signal end
< 
* Closing connection 0
```

While a request of 1024 bytes (note `printf '%820s'`) returns 101:
```
$ curl -v http://localhost:7890/ \
    -H 'Connection: Upgrade' \
    -H 'Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==' \
    -H 'Sec-WebSocket-Version: 13' \
    -H 'Upgrade: websocket' \
    -H 'User-Agent: Mozilla/5.0' \
    -H 'Cookie: foo='$(printf '%820s' | tr ' ' 'x')
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 7890 (#0)
> GET / HTTP/1.1
> Host: localhost:7890
> Accept: */*
> Connection: Upgrade
> Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==
> Sec-WebSocket-Version: 13
> Upgrade: websocket
> User-Agent: Mozilla/5.0
> Cookie: foo=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 
< HTTP/1.1 101 Switching Protocols
< Upgrade: websocket
< Connection: Upgrade
< Sec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=
< 
?;Y{"general": ...
```

**Comment by allinurl** [comment]
@ltm Thanks a lot for pointing this out. Let me try to reproduce this on my end and I'll post back.

**Comment by EpochalEngineer** [comment]
Did you have any success replicating?

I was able to replicate on my end with the curl commands and with a cookie set returning 400.  Opening goaccess incognito is successful.

**Comment by conet** [comment]
I can confirm that the problem was a too long cookie on that domain.

**Comment by allinurl** [comment]
Thanks for reporting this. I've added as a milestone for v1.4 which it's coming out soon.

**Comment by brunoluiz** [comment]
For anyone who comes across this issue and use traefik: you can remove the header by setting `Cookie=`. In my case, Cloudflare always adds a cookie to my requests, so it needs to be transformed traefik side. My docker-compose at the moment:

```
    labels:
      ...
      - "traefik.http.middlewares.removecookies.headers.customrequestheaders.Cookie="
      - "traefik.http.routers.goaccess.middlewares=removecookies"
```

**Comment by allinurl** [comment]
Thanks everyone, this has been fixed and pushed upstream. Feel free to test it [**out**](https://github.com/allinurl/goaccess#build-from-github-development).

This was compiler dependent as it was using `BUFSIZ`. It now uses a more reasonable fixed buffer size for the request headers of **`8192`**. It will be pushed out in the upcoming release. Stay tuned :)

**Comment by synthead** [comment]
I'm still getting this error with the latest tag (1.5.2) and the latest commit from master as of this writing (f7b1e3ce1f40e251c43dacd34e8dd632041d2d9c):

![image](https://user-images.githubusercontent.com/820984/137302747-16e30a5f-1af7-4a49-9c18-b98dd67ae949.png)

**Comment by aqos156** [comment]
I'm facing the same issue on latest docker image

**Comment by allinurl** [comment]
@aqos156 can you please share some details on your environment and the exact error you are getting via the browser's console and if you could try accessing `telnet host 7890`. thanks.

**Comment by aqos156** [comment]
@allinurl when I run `cat traefik.log | docker run --rm -i allinurl/goaccess -a -o html --log-format COMBINED - > report.html` then report.html is generated as expected. When I try to use the web server example from docs `cat traefik.log | docker run -p 7890:7890 --rm -i allinurl/goaccess -a -o html --log-format COMBINED --real-time-html - > report.html`

here is excempt from docs ![Snímek obrazovky 2022-01-24 v 15 56 17](https://user-images.githubusercontent.com/11147374/150806457-95e7a71f-8a40-44bc-bd1b-61201f4ad46f.png)

Is there anything more I have to do? The way I understand this from the docs I expect this to work.

When I curl localhost:7890 I get the same responses with 400 error as mentioned before.

**Comment by aqos156** [comment]
@allinurl just to add, here is the telnet output
```
root@mp-01:~# telnet localhost 7890
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/1.0
Host: localhost

HTTP/1.1 400 Invalid Request

Connection closed by foreign host.
root@mp-01:~# 
```


Also both of the curl commands in [this](https://github.com/allinurl/goaccess/issues/969#issuecomment-481949155) comment work for me, but when I remove any upgrade headers it stops working and returns 400.

**Comment by allinurl** [comment]
@aqos156 Sorry for the late reply. I wonder if you are behind some sort of proxy? Sounds like an environment issue. Here's what I get on a fresh image:

![2022-01-31 21-43](https://user-images.githubusercontent.com/5005367/151909995-7c48a28d-667c-42e5-b102-8fe1b7a114eb.gif)

**Comment by eric-saintetienne** [comment]
It's not a proxy or environment issue, issuing curl from within the docker instance yields the 400 error:
```
/ # curl --insecure -v https://localhost:7890/
* Host localhost:7890 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:7890...
* connect to ::1 port 7890 from ::1 port 57902 failed: Connection refused
*   Trying 127.0.0.1:7890...
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / x25519 / RSASSA-PSS
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=portainer
*  start date: Jul 11 13:39:13 2025 GMT
*  expire date: Jul  9 13:39:13 2035 GMT
*  issuer: CN=portainer
*  SSL certificate verify result: self-signed certificate (18), continuing anyway.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
* Connected to localhost (127.0.0.1) port 7890
* using HTTP/1.x
> GET / HTTP/1.1
> Host: localhost:7890
> User-Agent: curl/8.12.1
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/1.1 400 Invalid Request
* no chunk, no close, no size. Assume close to signal end
< 
* TLSv1.3 (IN), TLS alert, close notify (256):
* abort upload
* shutting down connection #0
* TLSv1.3 (OUT), TLS alert, close notify (256):
```

I also noticed that /var/www/goaccess in the docker image is empty. No index files to serve may be the cause of the 400?

**Comment by allinurl** [comment]
@eric-saintetienne did you specified the ssl cert and key? also if using https, please ensure to use wss.
